name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Backend to EC2
    runs-on: ubuntu-latest

    steps:
      # ① リポジトリのコードをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # ② SSH用ディレクトリを作成
      - name: Create .ssh directory
        run: mkdir -p ~/.ssh

      # ③ 秘密鍵をセット（GitHub Secretから）
      - name: Add SSH private key
        run: echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa

      # ④ 権限を600に設定（安全な状態に）
      - name: Set SSH key permissions
        run: chmod 600 ~/.ssh/id_rsa

      # ⑤ EC2ホストを信頼済みに追加（初回接続の確認回避）
      - name: Add EC2 host to known_hosts
        run: ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      # ⑥ EC2にSSH接続し、デプロイコマンドを実行
      - name: SSH and deploy to EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "bash -s" << 'EOF'
            cd /home/ubuntu/CryptoLens/backend
            git pull origin main
            npm install
            npm run build
            pm2 stop backend || true
            pm2 delete backend || true
            pm2 start dist/index.js --name backend

          EOF
